package com.example.unigo.data

import android.os.Parcelable
import com.example.unigo.models.Department
import kotlinx.parcelize.Parcelize

@Parcelize
data class University(
    val name: String,
    val city: String,
    val type: String,
    val departments: List<Department> = emptyList()
) : Parcelable

object UniversityData {
    val universities = listOf(
        University("Abant İzzet Baysal Üniversitesi", "Bolu", "DEVLET"),
        University("Abdullah Gül Üniversitesi", "Kayseri", "DEVLET"),
        University("Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi", "Adana", "DEVLET"),
        University("Adıyaman Üniversitesi", "Adıyaman", "DEVLET"),
        University("Afyon Kocatepe Üniversitesi", "Afyonkarahisar", "DEVLET"),
        University("Ağrı İbrahim Çeçen Üniversitesi", "Ağrı", "DEVLET"),
        University("Akdeniz Üniversitesi", "Antalya", "DEVLET"),
        University("Aksaray Üniversitesi", "Aksaray", "DEVLET"),
        University("Alanya Alaaddin Keykubat Üniversitesi", "Antalya", "DEVLET"),
        University("Amasya Üniversitesi", "Amasya", "DEVLET"),
        University("Anadolu Üniversitesi", "Eskişehir", "DEVLET"),
        University("Ankara Hacı Bayram Veli Üniversitesi", "Ankara", "DEVLET"),
        University("Ankara Sosyal Bilimler Üniversitesi", "Ankara", "DEVLET"),
        University("Ankara Üniversitesi", "Ankara", "DEVLET"),
        University("Ankara Yıldırım Beyazıt Üniversitesi", "Ankara", "DEVLET"),
        University("Antalya Bilim Üniversitesi", "Antalya", "DEVLET"),
        University("Ardahan Üniversitesi", "Ardahan", "DEVLET"),
        University("Artvin Çoruh Üniversitesi", "Artvin", "DEVLET"),
        University("Atatürk Üniversitesi", "Erzurum", "DEVLET"),
        University("Aydın Adnan Menderes Üniversitesi", "Aydın", "DEVLET"),
        University("Balıkesir Üniversitesi", "Balıkesir", "DEVLET"),
        University("Bandırma Onyedi Eylül Üniversitesi", "Balıkesir", "DEVLET"),
        University("Bartın Üniversitesi", "Bartın", "DEVLET"),
        University("Batman Üniversitesi", "Batman", "DEVLET"),
        University("Bayburt Üniversitesi", "Bayburt", "DEVLET"),
        University("Bilecik Şeyh Edebali Üniversitesi", "Bilecik", "DEVLET"),
        University("Bingöl Üniversitesi", "Bingöl", "DEVLET"),
        University("Bitlis Eren Üniversitesi", "Bitlis", "DEVLET"),
        University("Boğaziçi Üniversitesi", "İstanbul", "DEVLET"),
        University("Burdur Mehmet Akif Ersoy Üniversitesi", "Burdur", "DEVLET"),
        University("Bursa Teknik Üniversitesi", "Bursa", "DEVLET"),
        University("Bursa Uludağ Üniversitesi", "Bursa", "DEVLET"),
        University("Çanakkale Onsekiz Mart Üniversitesi", "Çanakkale", "DEVLET"),
        University("Çankırı Karatekin Üniversitesi", "Çankırı", "DEVLET"),
        University("Çukurova Üniversitesi", "Adana", "DEVLET"),
        University("Dicle Üniversitesi", "Diyarbakır", "DEVLET"),
        University("Dokuz Eylül Üniversitesi", "İzmir", "DEVLET"),
        University("Düzce Üniversitesi", "Düzce", "DEVLET"),
        University("Ege Üniversitesi", "İzmir", "DEVLET"),
        University("Erciyes Üniversitesi", "Kayseri", "DEVLET"),
        University("Erzincan Binali Yıldırım Üniversitesi", "Erzincan", "DEVLET"),
        University("Erzurum Teknik Üniversitesi", "Erzurum", "DEVLET"),
        University("Eskişehir Osmangazi Üniversitesi", "Eskişehir", "DEVLET"),
        University("Eskişehir Teknik Üniversitesi", "Eskişehir", "DEVLET"),
        University("Fırat Üniversitesi", "Elazığ", "DEVLET"),
        University("Galatasaray Üniversitesi", "İstanbul", "DEVLET"),
        University("Gazi Üniversitesi", "Ankara", "DEVLET"),
        University("Gaziantep İslam Bilim ve Teknoloji Üniversitesi", "Gaziantep", "DEVLET"),
        University("Gaziantep Üniversitesi", "Gaziantep", "DEVLET"),
        University("Gaziosmanpaşa Üniversitesi", "Tokat", "DEVLET"),
        University("Gebze Teknik Üniversitesi", "Kocaeli", "DEVLET"),
        University("Giresun Üniversitesi", "Giresun", "DEVLET"),
        University("Gümüşhane Üniversitesi", "Gümüşhane", "DEVLET"),
        University("Hacettepe Üniversitesi", "Ankara", "DEVLET"),
        University("Hakkari Üniversitesi", "Hakkari", "DEVLET"),
        University("Harran Üniversitesi", "Şanlıurfa", "DEVLET"),
        University("Hitit Üniversitesi", "Çorum", "DEVLET"),
        University("Iğdır Üniversitesi", "Iğdır", "DEVLET"),
        University("İnönü Üniversitesi", "Malatya", "DEVLET"),
        University("İskenderun Teknik Üniversitesi", "Hatay", "DEVLET"),
        University("İstanbul Medeniyet Üniversitesi", "İstanbul", "DEVLET"),
        University("İstanbul Teknik Üniversitesi", "İstanbul", "DEVLET"),
        University("İstanbul Üniversitesi", "İstanbul", "DEVLET"),
        University("İstanbul Üniversitesi-Cerrahpaşa", "İstanbul", "DEVLET"),
        University("İzmir Bakırçay Üniversitesi", "İzmir", "DEVLET"),
        University("İzmir Demokrasi Üniversitesi", "İzmir", "DEVLET"),
        University("İzmir Kâtip Çelebi Üniversitesi", "İzmir", "DEVLET"),
        University("İzmir Yüksek Teknoloji Enstitüsü", "İzmir", "DEVLET"),
        University("Kafkas Üniversitesi", "Kars", "DEVLET"),
        University("Kahramanmaraş İstiklal Üniversitesi", "Kahramanmaraş", "DEVLET"),
        University("Kahramanmaraş Sütçü İmam Üniversitesi", "Kahramanmaraş", "DEVLET"),
        University("Karabük Üniversitesi", "Karabük", "DEVLET"),
        University("Karadeniz Teknik Üniversitesi", "Trabzon", "DEVLET"),
        University("Karamanoğlu Mehmetbey Üniversitesi", "Karaman", "DEVLET"),
        University("Kastamonu Üniversitesi", "Kastamonu", "DEVLET"),
        University("Kayseri Üniversitesi", "Kayseri", "DEVLET"),
        University("Kırıkkale Üniversitesi", "Kırıkkale", "DEVLET"),
        University("Kırklareli Üniversitesi", "Kırklareli", "DEVLET"),
        University("Kırşehir Ahi Evran Üniversitesi", "Kırşehir", "DEVLET"),
        University("Kilis 7 Aralık Üniversitesi", "Kilis", "DEVLET"),
        University("Kocaeli Üniversitesi", "Kocaeli", "DEVLET"),
        University("Konya Teknik Üniversitesi", "Konya", "DEVLET"),
        University("Kütahya Dumlupınar Üniversitesi", "Kütahya", "DEVLET"),
        University("Kütahya Sağlık Bilimleri Üniversitesi", "Kütahya", "DEVLET"),
        University("Malatya Turgut Özal Üniversitesi", "Malatya", "DEVLET"),
        University("Manisa Celal Bayar Üniversitesi", "Manisa", "DEVLET"),
        University("Mardin Artuklu Üniversitesi", "Mardin", "DEVLET"),
        University("Marmara Üniversitesi", "İstanbul", "DEVLET"),
        University("Mersin Üniversitesi", "Mersin", "DEVLET"),
        University("Mimar Sinan Güzel Sanatlar Üniversitesi", "İstanbul", "DEVLET"),
        University("Muğla Sıtkı Koçman Üniversitesi", "Muğla", "DEVLET"),
        University("Munzur Üniversitesi", "Tunceli", "DEVLET"),
        University("Muş Alparslan Üniversitesi", "Muş", "DEVLET"),
        University("Necmettin Erbakan Üniversitesi", "Konya", "DEVLET"),
        University("Nevşehir Hacı Bektaş Veli Üniversitesi", "Nevşehir", "DEVLET"),
        University("Niğde Ömer Halisdemir Üniversitesi", "Niğde", "DEVLET"),
        University("Ondokuz Mayıs Üniversitesi", "Samsun", "DEVLET"),
        University("Ordu Üniversitesi", "Ordu", "DEVLET"),
        University("Orta Doğu Teknik Üniversitesi", "Ankara", "DEVLET"),
        University("Osmaniye Korkut Ata Üniversitesi", "Osmaniye", "DEVLET"),
        University("Pamukkale Üniversitesi", "Denizli", "DEVLET"),
        University("Recep Tayyip Erdoğan Üniversitesi", "Rize", "DEVLET"),
        University("Sakarya Üniversitesi", "Sakarya", "DEVLET"),
        University("Samsun Üniversitesi", "Samsun", "DEVLET"),
        University("Selçuk Üniversitesi", "Konya", "DEVLET"),
        University("Siirt Üniversitesi", "Siirt", "DEVLET"),
        University("Sinop Üniversitesi", "Sinop", "DEVLET"),
        University("Sivas Bilim ve Teknoloji Üniversitesi", "Sivas", "DEVLET"),
        University("Sivas Cumhuriyet Üniversitesi", "Sivas", "DEVLET"),
        University("Süleyman Demirel Üniversitesi", "Isparta", "DEVLET"),
        University("Şırnak Üniversitesi", "Şırnak", "DEVLET"),
        University("Tarsus Üniversitesi", "Mersin", "DEVLET"),
        University("Tekirdağ Namık Kemal Üniversitesi", "Tekirdağ", "DEVLET"),
        University("Tokat Gaziosmanpaşa Üniversitesi", "Tokat", "DEVLET"),
        University("Trabzon Üniversitesi", "Trabzon", "DEVLET"),
        University("Türk-Alman Üniversitesi", "İstanbul", "DEVLET"),
        University("Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi", "İstanbul", "DEVLET"),
        University("Uşak Üniversitesi", "Uşak", "DEVLET"),
        University("Van Yüzüncü Yıl Üniversitesi", "Van", "DEVLET"),
        University("Yalova Üniversitesi", "Yalova", "DEVLET"),
        University("Yıldız Teknik Üniversitesi", "İstanbul", "DEVLET"),
        University("Yozgat Bozok Üniversitesi", "Yozgat", "DEVLET"),
        University("Zonguldak Bülent Ecevit Üniversitesi", "Zonguldak", "DEVLET"),

        // Vakıf Üniversiteleri
        University("Acıbadem Üniversitesi", "İstanbul", "VAKIF"),
        University("Alanya Alaaddin Keykubat Üniversitesi", "Antalya", "VAKIF"),
        University("Alanya Hamdullah Emin Paşa Üniversitesi", "Antalya", "VAKIF"),
        University("Altınbaş Üniversitesi", "İstanbul", "VAKIF"),
        University("Ankara Medipol Üniversitesi", "Ankara", "VAKIF"),
        University("Antalya Akev Üniversitesi", "Antalya", "VAKIF"),
        University("Atılım Üniversitesi", "Ankara", "VAKIF"),
        University("Avrasya Üniversitesi", "Trabzon", "VAKIF"),
        University("Bahçeşehir Üniversitesi", "İstanbul", "VAKIF"),
        University("Başkent Üniversitesi", "Ankara", "VAKIF"),
        University("Beykent Üniversitesi", "İstanbul", "VAKIF"),
        University("Bezm-i Alem Vakıf Üniversitesi", "İstanbul", "VAKIF"),
        University("Biruni Üniversitesi", "İstanbul", "VAKIF"),
        University("Çağ Üniversitesi", "Mersin", "VAKIF"),
        University("Çankaya Üniversitesi", "Ankara", "VAKIF"),
        University("Doğuş Üniversitesi", "İstanbul", "VAKIF"),
        University("Fenerbahçe Üniversitesi", "İstanbul", "VAKIF"),
        University("Gedik Üniversitesi", "İstanbul", "VAKIF"),
        University("Haliç Üniversitesi", "İstanbul", "VAKIF"),
        University("Işık Üniversitesi", "İstanbul", "VAKIF"),
        University("İbn Haldun Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul 29 Mayıs Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Arel Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Aydın Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Bilgi Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Esenyurt Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Gedik Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Gelişim Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Kemerburgaz Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Kent Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Kültür Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Medipol Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Nişantaşı Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Okan Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Rumeli Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Sabahattin Zaim Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Şehir Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Ticaret Üniversitesi", "İstanbul", "VAKIF"),
        University("İzmir Ekonomi Üniversitesi", "İzmir", "VAKIF"),
        University("İzmir Kâtip Çelebi Üniversitesi", "İzmir", "VAKIF"),
        University("Kadir Has Üniversitesi", "İstanbul", "VAKIF"),
        University("Koç Üniversitesi", "İstanbul", "VAKIF"),
        University("Maltepe Üniversitesi", "İstanbul", "VAKIF"),
        University("MEF Üniversitesi", "İstanbul", "VAKIF"),
        University("Nişantaşı Üniversitesi", "İstanbul", "VAKIF"),
        University("Nuh Naci Yazgan Üniversitesi", "Kayseri", "VAKIF"),
        University("Özyeğin Üniversitesi", "İstanbul", "VAKIF"),
        University("Piri Reis Üniversitesi", "İstanbul", "VAKIF"),
        University("Sabancı Üniversitesi", "İstanbul", "VAKIF"),
        University("Sanko Üniversitesi", "Gaziantep", "VAKIF"),
        University("TED Üniversitesi", "Ankara", "VAKIF"),
        University("TOBB Ekonomi ve Teknoloji Üniversitesi", "Ankara", "VAKIF"),
        University("Toros Üniversitesi", "Mersin", "VAKIF"),
        University("Ufuk Üniversitesi", "Ankara", "VAKIF"),
        University("Üsküdar Üniversitesi", "İstanbul", "VAKIF"),
        University("Yaşar Üniversitesi", "İzmir", "VAKIF"),
        University("Yeditepe Üniversitesi", "İstanbul", "VAKIF"),
        University("Yeni Yüzyıl Üniversitesi", "İstanbul", "VAKIF"),
        University("Yüksek İhtisas Üniversitesi", "Ankara", "VAKIF"),
        University("Zirve Üniversitesi", "Gaziantep", "VAKIF"),
        // İstanbul'daki eksik vakıf üniversiteleri
        University("Beykoz Üniversitesi", "İstanbul", "VAKIF"),
        University("Üsküdar Üniversitesi", "İstanbul", "VAKIF"),
        University("Bezmialem Vakıf Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Atlas Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Galata Üniversitesi", "İstanbul", "VAKIF"),
        University("İstanbul Sağlık ve Teknoloji Üniversitesi", "İstanbul", "VAKIF"),
        University("İstinye Üniversitesi", "İstanbul", "VAKIF"),
        // Vakıf Meslek Yüksekokulları (MYO)
        University("İstanbul Şişli Meslek Yüksekokulu", "İstanbul", "VAKIF"),
        University("Ataşehir Adıgüzel Meslek Yüksekokulu", "İstanbul", "VAKIF"),
        University("İstanbul Sağlık ve Sosyal Bilimler Meslek Yüksekokulu", "İstanbul", "VAKIF"),
        University("Isparta Uygulamalı Bilimler Üniversitesi", "Isparta", "VAKIF"),
        University("Sakarya Uygulamalı Bilimler Üniversitesi", "Sakarya", "VAKIF"),
        University("Ankara Bilim Üniversitesi", "Ankara", "VAKIF"),
        University("Kocaeli Sağlık ve Teknoloji Üniversitesi", "Kocaeli", "VAKIF"),
        University("Konya Gıda ve Tarım Üniversitesi", "Konya", "VAKIF"),
        University("Lokman Hekim Üniversitesi", "Ankara", "VAKIF"),
        University("İstanbul Topkapı Üniversitesi", "İstanbul", "VAKIF"),
        University("Avrupa Meslek Yüksekokulu", "İstanbul", "VAKIF")
    ).sortedBy { it.name }
}